In [9]:
import torch

print(torch.cuda.is_available())
print(torch.__version__)

False
2.5.1+cu118


### 3 main issues
1. tensors not right datatype
2. tensors not right shape (dimensions)
3. tensors not on right device (cpu vs gpu)

In [13]:
# Tensors
tensor0d = torch.tensor(7)
print(tensor0d, tensor0d.shape, tensor0d.ndim)

tensor1d = torch.tensor([4, 5, 6, 7, 8, 123412])
print(tensor1d, tensor1d.shape, tensor1d.ndim)

tensor(7) torch.Size([]) 0
tensor([     4,      5,      6,      7,      8, 123412]) torch.Size([6]) 1


torch.Size([])
torch.Size([2])


In [12]:
#2d tensor
tensor2d = torch.tensor([[1, 2],
                         [2, 3], 
                         [3, 4]])
print(tensor2d, tensor2d.shape, tensor2d.ndim)

tensor([[1, 2],
        [2, 3],
        [3, 4]]) torch.Size([3, 2]) 2


### Notes:
- ndim = 0: scalar (0d arr?)
- ndim = 1: vector (1d array)
- ndim = 2: matrix (2d array)
- ndim = 3: 3d array


- ndim = # of elements in tensor.shape array

In [17]:
## Random tensors
rand = torch.rand(size=[3, 4])       #last two are always row, col
print(rand, rand.shape, rand.ndim)

tensor([[0.9712, 0.1927, 0.6851, 0.5629],
        [0.9805, 0.4831, 0.6496, 0.5737],
        [0.3492, 0.0611, 0.1841, 0.2373]]) torch.Size([3, 4]) 2


In [20]:
## 0 tensors
zeros = torch.zeros(size=[3, 4])
print(zeros, zeros.shape, zeros.ndim)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) torch.Size([3, 4]) 2


In [28]:
a = torch.tensor([[1, 0, 0, 0],
                 [0, 1, 0, 0],
                 [0, 0, 1, 0]])

rand * a


tensor([[0.9712, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.4831, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.1841, 0.0000]])

In [51]:
#python range, but for pytorch
torch_vector = torch.arange(start=0, end=10, step=0.2)

print(torch_vector, torch_vector.shape)

tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000, 1.0000, 1.2000, 1.4000, 1.6000,
        1.8000, 2.0000, 2.2000, 2.4000, 2.6000, 2.8000, 3.0000, 3.2000, 3.4000,
        3.6000, 3.8000, 4.0000, 4.2000, 4.4000, 4.6000, 4.8000, 5.0000, 5.2000,
        5.4000, 5.6000, 5.8000, 6.0000, 6.2000, 6.4000, 6.6000, 6.8000, 7.0000,
        7.2000, 7.4000, 7.6000, 7.8000, 8.0000, 8.2000, 8.4000, 8.6000, 8.8000,
        9.0000, 9.2000, 9.4000, 9.6000, 9.8000]) torch.Size([50])


In [52]:
zeros_like = torch.zeros_like(torch_vector)
zeros_like, zeros_like.shape

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.]),
 torch.Size([50]))

# Datatypes

In [85]:
ten = torch.rand([3, 2])
ten.dtype

torch.float32

# Tensor Math

In [64]:
#addition, subtraction

a = torch.ones(size=[2, 3])
b = torch.ones(size=[2, 3])
c = torch.ones(size=[3, 3])

print(f'a: {a}')
print(f'b: {b}')
print(f'c: {c}')



print(f'a + b: \n{a+b}')
print(f'a-b: \n{a-b}')
print()
print(f'[2x3] + [3x3]: \n{a+c}')


a: tensor([[1., 1., 1.],
        [1., 1., 1.]])
b: tensor([[1., 1., 1.],
        [1., 1., 1.]])
c: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
a + b: 
tensor([[2., 2., 2.],
        [2., 2., 2.]])
a-b: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])



RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0

In [70]:
# element-wise add, subtract, multiply, divide
tensor = torch.arange(0, 3, 1)
print(tensor)

print(tensor + 10)
print(tensor - 10)
print(tensor * 3)
print(tensor / 3)
print(tensor.dtype)

tensor([0, 1, 2])
tensor([10, 11, 12])
tensor([-10,  -9,  -8])
tensor([0, 3, 6])
tensor([0.0000, 0.3333, 0.6667])
torch.int64


### Matrix multiplication

- 1d matmul 1d is just dot product between 2 vector

In [ ]:
#vector matmul vector ==> dot product
# (1*1) + (2*2)
tensor = torch.tensor([1, 2])
print(torch.matmul(tensor, tensor))

tensor(5)


In [ ]:
#matrix multiplication

a = torch.rand(size=[2, 3])
b = torch.rand(size=[3, 5])
res = torch.matmul(a, b)
print(res, res.shape, res.ndim) # [2, 5], 2

tensor([[0.1681, 0.9938, 1.3125, 1.0815, 0.8810],
        [0.2790, 0.8642, 1.0421, 0.9299, 0.3567]]) torch.Size([2, 5]) 2


In [ ]:
#3d matmul
a = torch.ones(size=[3, 3, 2])
b = torch.ones(size=[3, 2, 3])

c = torch.matmul(a, b)
print(c, c.shape, c.ndim)

print('[3x3x2] @ [3x2x3] = [3x3x3]')


tensor([[[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]]]) torch.Size([3, 3, 3]) 3
[3x3x2] @ [3x2x3] = [3x3x3]


In [78]:
#4d matmul
print('[c, z, m, n] @ [c, z, n, r] = [c, z, m, r]')

[c, z, m, n] @ [c, z, n, r] = [c, z, m, r]


### min, max , mean ,sum

In [79]:
#Values

tensorx = torch.arange(0, 10, 1).type(dtype=torch.float32)
print(tensorx)

print(f"min: {tensorx.min()}")
print(f"max: {tensorx.max()}")
print(f"mean: {tensorx.mean()}") #torch.mean requires float32 input type
print(f"sum: {tensorx.sum()}")
tensorx.mean()

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
min: 0.0
max: 9.0
mean: 4.5
sum: 45.0


tensor(4.5000)

In [80]:
#positional min and max
#finds the index of the min and max
print(tensorx)
print(tensorx.argmin(), tensorx[tensorx.argmin()])
print(tensorx.argmax(), tensorx[tensorx.argmax()])


tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor(0) tensor(0.)
tensor(9) tensor(9.)


# Reshape, views, stacking, squeezing, unsqueezing tensors

Reshape: change shape of input tensor into a different defined shape
view: returns view of input tensor (a view of a tensor shares the same memory as the orginal tensor)

changing a view of tensor x changes tensor x